### Create a chat
POST {{host}}/api/v1/chat
Content-Type: application/json

{
  "participant_ids": ["{{userId1}}", "{{userId2}}"]
}

### Send a message to a chat
POST {{host}}/api/v1/chat/{{chatId}}
Content-Type: application/json

{
  "sender_id": "{{userId2}}",
  "body": "last test I think v2",
  "msg_type": 0,
  "dedupe_key": "optional-dedupe-key"
}

### Get messages from a chat
GET {{host}}/api/v1/chat/{{chatId}}/messages?limit=50&offset=0
